# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Nstatis"
license = "MIT"
licenselink = "https://github.com/Ikhsan/Nstatis/blob/master/LICENSE"
description = "A Personal Site"
homepage = "https://nashki.dev/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ikhsan Nur Huda"
  homepage = ""


